### ISSUE TITLE
Do you have any progress ?

### ISSUE THREAD

**Issue by gaopeng-eugene** [hiwonjoon/tf-vqvae#1]

**Comment by hiwonjoon** [comment]
I have no plan yet to reproduce their results; first, there is no available pixel CNN model for ImageNet, and second, I cannot currently figure out what they mean by using the pre-trained network as a prior for z.

Nevertheless, any contributions or discussions are welcome!
Thanks.

**Comment by hiwonjoon** [comment]
Hello,

I implemented sampling procedure by training prior Z using pixelCNN. Please check the code and results. The result for MNIST seems good (as always, everyone is happy with MNIST) while the result for CIFAR10 seems (only) acceptable.

Further comments and contributions are still welcome!
Thanks.
